### PR TITLE
Feature/updated ui

### PR DESCRIPTION
**Pull request by Noeza**
Updated to the UI to the new design that caters for the  web responsiveness and added the google fonts to the project too.

### CODE REVIEW

**Comment by Noeza** [comment]
@michaeldera I am stilling working on this. Please dont merge it.

**Comment by michaeldera** [comment]
> @michaeldera I am stilling working on this. Please dont merge it.

You know there are draft PRs on GitHub now right?

**Comment by michaeldera** [comment]
Please do remember to let me know once this is done because I know I am meant to ignore it for now.

**Comment by Noeza** [comment]
I will, the UI is done, i was cleaning the code for now after adding linting and prettier rules.

**Comment by Noeza** [comment]
@michaeldera I am done here. Please test too.

**Comment by Noeza** [comment]
If you are happy, you can merge to develop

**Pull request merged**
