### PR TITLE
Performance Improvements & Reader design update

### PR DESCRIPTION
**Pull request by Noeza**
1. Improved the developer experience by adding babel. The issue we had here was that typescript was compiling the entire project when ever a file is changed, which took time for the project to load to be able to view the changes. Not ideal situation, thus I:
- Created a startup script inspired by CRA's script.
- Use react-dev-utils to improve the local dev experience. This is the same CLI UI as CRA. No more annoying Web-pack log messages!!
- Replace awesome-typescript-loader with a combo of babel and async type checking.
- Add and configure react-hot-loader.
2. I have updated the css styling to use styled-components, as i thought it would be best to adopt the CSS-In-JS technique to improve the performance of the application to reduce the amount of class div and css files which gets bulky, clumsy and very complex. 
3. I have added alias to replace absolute paths.
4. I have updated the reading page for the desktop version.

### CODE REVIEW

**Comment by michaeldera** [comment]
Is this ready for review and merging?

**Comment by Noeza** [comment]
> Is this ready for review and merging?

Yap, sorry i forgot to remove that label

**Comment by michaeldera** [comment]
This is breaking the build so I reverted it. Are there changes to the build scripts?

**Comment by Noeza** [comment]
> This is breaking the build so I reverted it. Are there changes to the build scripts?
On which is your build script?

**Comment by michaeldera** [comment]
Seems Azure DevOps is down at the moment but basically check if `yarn build` works on your end.

**Comment by Noeza** [comment]
> Seems Azure DevOps is down at the moment but basically check if `yarn build` works on your end.

I think i have an idea why it is failing, i did make changes to the build script, we might need to make 1 or two changes on Azue

**Pull request merged**
