### PR TITLE
Feature/infomation

### PR DESCRIPTION
**Pull request by Noeza**
Refactored the Information Page, and added scroll to  top buttons.

### CODE REVIEW

**Comment by Noeza** [comment]
@michaeldera pardon me which blue are you referring to?

**Comment by michaeldera** [comment]
If you on localhost it is on localhost/#/information

**Comment by Noeza** [comment]
yes it it,
image
 I changed the scroll to to button to use the RoundedButton component.

**Comment by michaeldera** [comment]
This is th epage I am referring to. The change in ui went with some css that made the text links a white and underlined instead. So that is where I was requesting changes, The css should be pretty much the same as the homepage. 

localhost_3000_

**Comment by Noeza** [comment]
Is this it
image
If i am not understanding you, we can hop on a call.

**Comment by michaeldera** [comment]
> Is this it
> image
> If i am not understanding you, we can hop on a call.

Yes that is cool. That is not what is on the PR is it?

**Comment by Noeza** [comment]
I have updated the PR

**Comment by michaeldera** [comment]
> I have updated the PR

Cool. Let me get to it.

**Pull request merged**
